//====================================================================================
### GET categories
GET http://localhost:7878/api/v1/categories
//------------------------------------------------------------------------------------
### GET categoriesById
GET http://localhost:7878/api/v1/categories/7e0513b7-1e13-4c6e-a55e-0cb0d6a8e6d8
//------------------------------------------------------------------------------------
### POST categories
POST http://localhost:7878/api/v1/categories
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "categoryName": "TestUser2!"
}
###
//------------------------------------------------------------------------------------
### PUT category
PUT http://localhost:7878/api/v1/categories/b643802b-eb13-4137-99ea-45356c2eba3d
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "categoryName": "CS Premium"
}
###
//------------------------------------------------------------------------------------
### DELETE category
DELETE http://localhost:7878/api/v1/categories/b643802b-eb13-4137-99ea-45356c2eba3d
Authorization: Bearer {{$auth.token("keycloak")}}

//------------------------------------------------------------------------------------





//====================================================================================
### GET subscriptions
GET http://localhost:7878/api/v1/subscriptions/all
Authorization: Bearer {{$auth.token("keycloak")}}
//------------------------------------------------------------------------------------
### GET subscriptionsById
GET http://localhost:7878/api/v1/subscriptions/9e26d6eb-9c24-4e01-bd76-24a311bb9cdd

//------------------------------------------------------------------------------------
### GET subscriptionsUsersById
GET http://localhost:7878/api/v1/subscriptions
Authorization: Bearer {{$auth.token("keycloak")}}

//------------------------------------------------------------------------------------
### POST subscription
POST http://localhost:7878/api/v1/subscriptions
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "serviceName": "Dota+",
  "nextPaymentDate": "2024-07-25T00:00:00",
  "amount": 200,
  "currency": "USD",
  "categoryId": "62b6bb1c-7289-4071-ae22-06244650df4f"
}
###
//------------------------------------------------------------------------------------
### PUT subscription
PUT http://localhost:7878/api/v1/subscriptions/a6f48255-e73d-4fe9-94e1-4ddb3d52704c
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "serviceName": "Dota10+",
  "nextPaymentDate": "2024-07-24T00:00:00",
  "amount": 300,
  "currency": "USD",
  "categoryId": "3ab672c0-9364-498c-9358-fb23a13f9a3a"
}

###
//------------------------------------------------------------------------------------
### DELETE category
DELETE http://localhost:7878/api/v1/subscriptions/7e0513b7-1e13-4c6e-a55e-0cb0d6a8e6d8

//------------------------------------------------------------------------------------
### GET total amount for each category
GET http://localhost:7878/api/v1/subscriptions/total-amounts
