//====================================================================================
### GET categories
GET http://localhost:7878/api/v1/categories
//------------------------------------------------------------------------------------
### GET categoriesById
GET http://localhost:7878/api/v1/categories/9637be53-789b-4e0c-baca-ea7fb6244241
//------------------------------------------------------------------------------------
### POST categories
POST http://localhost:7878/api/v1/categories
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "categoryName": "TestUser3!"
}
###
//------------------------------------------------------------------------------------
### PUT category
PUT http://localhost:7878/api/v1/categories/9637be53-789b-4e0c-baca-ea7fb6244241
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "categoryName": "CS Premium"
}
###
//------------------------------------------------------------------------------------
### DELETE category
DELETE http://localhost:7878/api/v1/categories/37ad0fc1-43d6-4e9d-b412-868a16a3c96e
Authorization: Bearer {{$auth.token("keycloak")}}

//------------------------------------------------------------------------------------





//====================================================================================
### GET subscriptions
GET http://localhost:7878/api/v1/subscriptions/all
Authorization: Bearer {{$auth.token("keycloak")}}
//------------------------------------------------------------------------------------
### GET subscriptionsById
GET http://localhost:7878/api/v1/subscriptions/9e26d6eb-9c24-4e01-bd76-24a311bb9cdd

//------------------------------------------------------------------------------------
### GET subscriptionsUsersById
GET http://localhost:7878/api/v1/subscriptions
Authorization: Bearer {{$auth.token("keycloak")}}

//------------------------------------------------------------------------------------
### POST subscription
POST http://localhost:7878/api/v1/subscriptions
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "serviceName": "Dota4+",
  "nextPaymentDate": "2024-07-25T00:00:00",
  "amount": 500,
  "currency": "USD",
  "categoryId": "9637be53-789b-4e0c-baca-ea7fb6244241"
}
###
//------------------------------------------------------------------------------------
### PUT subscription
PUT http://localhost:7878/api/v1/subscriptions/9596c308-857a-425a-9e20-1527820bd09e
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "serviceName": "Dota2+",
  "nextPaymentDate": "2024-07-24T00:00:00",
  "amount": 500,
  "currency": "USD",
  "categoryId": "9637be53-789b-4e0c-baca-ea7fb6244241"
}

###
//------------------------------------------------------------------------------------
### DELETE category
DELETE http://localhost:7878/api/v1/subscriptions/92d26e69-5bcc-450f-8f3c-8ab5b48d2f83

//------------------------------------------------------------------------------------
### GET total amount for each category
GET http://localhost:7878/api/v1/subscriptions/total-amounts
