//====================================================================================
### GET categories
GET http://localhost:7878/api/v1/categories
//------------------------------------------------------------------------------------
### GET categoriesById
GET http://localhost:7878/api/v1/categories/ad1c8a8e-a415-49a5-b092-fcc6d94338cc
//------------------------------------------------------------------------------------
### POST categories
POST http://localhost:7878/api/v1/categories
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "categoryName": "Edu"
}
###
//------------------------------------------------------------------------------------
### PUT category
PUT http://localhost:7878/api/v1/categories/a0b262a2-3a20-4aa2-a887-c19027784033
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "categoryName": "Game"
}
###
//------------------------------------------------------------------------------------
### DELETE category
DELETE http://localhost:7878/api/v1/categories/e4cab9b9-65d9-4be7-b792-9edbd4079315
Authorization: Bearer {{$auth.token("keycloak")}}

//------------------------------------------------------------------------------------





//====================================================================================
### GET subscriptions
GET http://localhost:7878/api/v1/subscriptions/all
Authorization: Bearer {{$auth.token("keycloak")}}
//------------------------------------------------------------------------------------
### GET subscriptionsById
GET http://localhost:7878/api/v1/subscriptions/1007943a-deed-4331-a22a-21fe0fb0d32f

//------------------------------------------------------------------------------------
### GET subscriptionsUsersById
GET http://localhost:7878/api/v1/subscriptions
Authorization: Bearer {{$auth.token("keycloak")}}

//------------------------------------------------------------------------------------
### POST subscription
POST http://localhost:7878/api/v1/subscriptions
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "serviceName": "Dota",
  "nextPaymentDate": "2024-07-25T00:00:00",
  "amount": 5,
  "currency": "USD",
  "categoryId": "44be70b8-5599-42e9-ac4a-eadfd6ed70ce"
}
###
//------------------------------------------------------------------------------------
### PUT subscription
PUT http://localhost:7878/api/v1/subscriptions/baf36250-6817-4ff0-ae35-8e08aac44383
Authorization: Bearer {{$auth.token("keycloak")}}
Content-Type: application/json

{
  "serviceName": "Spotify",
  "nextPaymentDate": "2024-07-24T00:00:00",
  "amount": 500,
  "currency": "USD",
  "categoryId": "ad1c8a8e-a415-49a5-b092-fcc6d94338cc"
}

###
//------------------------------------------------------------------------------------
### DELETE category
DELETE http://localhost:7878/api/v1/subscriptions/682ac8ce-4d60-4f18-b5d6-148022d4d271

//------------------------------------------------------------------------------------
### GET total amount for each category
GET http://localhost:7878/api/v1/subscriptions/total-amounts
